from django.db import models

#import sys
#sys.path.append('..')


STRAND = (('+','+'),('-','-'))
SEQTYPE = (('A','All'),('E','Exon'),('I','Intron'),('O','Other'))
EXOTYPE = (('A','All'),('C','CDS'),('5','5\'UTR'),('3','3\'UTR'))
DNA = (('A','A'),('C','C'),('G','G'),('T','T'))
RNA = (('A','A'),('C','C'),('G','G'),('I','I'),('U','U'))


class Gene(models.Model):
    geneid = models.IntegerField()
    gene = models.CharField(max_length=10)
    geneWiki = models.URLField()

class Source(models.Model):
    source = models.CharField(max_length=50)


class PubMed(models.Model):
    pubid = models.IntegerField()
    author = models.CharField(max_length=32)
    year = models.IntegerField()

class Hg18_Chr1(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

    

class Hg18_Chr2(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr3(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr4(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr5(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr6(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr7(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr8(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr9(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr10(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr11(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr12(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr13(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr14(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr15(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr16(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr17(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr18(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr19(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr20(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr21(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_Chr22(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_ChrX(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg18_ChrY(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

#=======Assembly hg19=========

class Hg19_Chr1(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr2(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr3(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr4(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr5(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr6(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr7(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr8(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr9(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr10(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr11(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr12(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr13(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr14(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr15(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr16(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr17(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr18(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr19(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr20(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr21(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_Chr22(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_ChrX(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

class Hg19_ChrY(models.Model):
    coordinate = models.IntegerField()
    strand = models.CharField(choices=STRAND,max_length=1)
    indna = models.CharField(choices=DNA,max_length=1)
    inref = models.CharField(choices=DNA,max_length=1)
    inrna = models.CharField(choices=RNA,max_length=1)
    seqtype = models.CharField(choices = SEQTYPE,max_length=1)
    exotype = models.CharField(choices = EXOTYPE,max_length=1)
    gene = models.ForeignKey(Gene)
    source = models.ManyToManyField(Source)
    pubid = models.ManyToManyField(PubMed)

# Create your models here.
